# Generated by Django 5.0.2 on 2024-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
